import productImage from "@/assets/Products/Product1.jpg";
import { Product } from "@/types/product/productCard";

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "Experience crystal-clear sound with our noise-cancelling wireless headphones.",
    price: 199.99,
    originalPrice: 249.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.5,
    reviewCount: 124,
    isNew: true,
    isSale: true,
    tags: ["Wireless", "Noise Cancelling", "Bluetooth"]
  },
  {
    id: "2",
    name: "Minimalist Watch",
    description: "Elegant timepiece with leather strap and sapphire glass.",
    price: 159.99,
    imageUrl: productImage.src,
    category: "Accessories",
    rating: 4.8,
    reviewCount: 89,
    isNew: false,
    isSale: false,
    tags: ["Leather", "Analog", "Water Resistant"]
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and sustainable t-shirt made from 100% organic cotton.",
    price: 29.99,
    originalPrice: 39.99,
    imageUrl: productImage.src,
    category: "Clothing",
    rating: 4.3,
    reviewCount: 67,
    isNew: false,
    isSale: true,
    tags: ["Organic", "Sustainable", "Comfort Fit"]
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and sustainable t-shirt made from 100% organic cotton.",
    price: 29.99,
    originalPrice: 39.99,
    imageUrl: productImage.src,
    category: "Clothing",
    rating: 4.3,
    reviewCount: 67,
    isNew: false,
    isSale: true,
    tags: ["Organic", "Sustainable", "Comfort Fit"]
  },
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "Experience crystal-clear sound with our noise-cancelling wireless headphones.",
    price: 199.99,
    originalPrice: 249.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.5,
    reviewCount: 124,
    isNew: true,
    isSale: true,
    tags: ["Wireless", "Noise Cancelling", "Bluetooth"]
  },
  {
    id: "2",
    name: "Minimalist Watch",
    description: "Elegant timepiece with leather strap and sapphire glass.",
    price: 159.99,
    imageUrl: productImage.src,
    category: "Accessories",
    rating: 4.8,
    reviewCount: 89,
    isNew: false,
    isSale: false,
    tags: ["Leather", "Analog", "Water Resistant"]
  },
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "Experience crystal-clear sound with our noise-cancelling wireless headphones.",
    price: 199.99,
    originalPrice: 249.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.5,
    reviewCount: 124,
    isNew: true,
    isSale: true,
    tags: ["Wireless", "Noise Cancelling", "Bluetooth"]
  },
  {
    id: "2",
    name: "Minimalist Watch",
    description: "Elegant timepiece with leather strap and sapphire glass.",
    price: 159.99,
    imageUrl: productImage.src,
    category: "Accessories",
    rating: 4.8,
    reviewCount: 89,
    isNew: false,
    isSale: false,
    tags: ["Leather", "Analog", "Water Resistant"]
  },
];