import productImage from "../../../public/Product1.jpg";
import { Product } from "@/types/product/productCard";

export const sampleProducts: Product[] = [
  {
    id: "1",
    slug: "premium-wireless-headphones",
    name: "Premium Wireless Headphones",
    description:
      "Experience crystal-clear sound with our premium wireless headphones, designed for both music lovers and professionals. Featuring advanced noise-cancelling technology, you can enjoy your favorite tracks, podcasts, or calls without distractions from the outside world. The lightweight design and cushioned ear cups ensure all-day comfort, while the long-lasting battery gives you up to 30 hours of uninterrupted playtime. With Bluetooth 5.0 connectivity, seamless pairing, and built-in controls, staying connected has never been easier. Whether you’re working, traveling, or relaxing, these headphones deliver exceptional sound quality and convenience.",
    price: 199.99,
    originalPrice: 249.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 5,
    reviewCount: 124,
    isNew: true,
    isSale: true,
    tags: ["Wireless", "Noise Cancelling", "Bluetooth"],
  },
  {
    id: "2",
    slug: "minimalist-watch",
    name: "Minimalist Watch",
    description: "Elegant timepiece with leather strap and sapphire glass.",
    price: 159.99,
    imageUrl: productImage.src,
    category: "Accessories",
    rating: 4,
    reviewCount: 89,
    isNew: false,
    isSale: false,
    tags: ["Leather", "Analog", "Water Resistant"],
  },
  {
    id: "3",
    slug: "organic-cotton-tshirt",
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and sustainable t-shirt made from 100% organic cotton.",
    price: 29.99,
    originalPrice: 39.99,
    imageUrl: productImage.src,
    category: "Clothing",
    rating: 3,
    reviewCount: 67,
    isNew: false,
    isSale: true,
    tags: ["Organic", "Sustainable", "Comfort Fit"],
  },
  {
    id: "4",
    slug: "leather-backpack",
    name: "Leather Backpack",
    description: "Handcrafted leather backpack perfect for work, travel, or casual outings.",
    price: 129.99,
    originalPrice: 179.99,
    imageUrl: productImage.src,
    category: "Accessories",
    rating: 4.6,
    reviewCount: 54,
    isNew: true,
    isSale: true,
    tags: ["Leather", "Handmade", "Travel"],
  },
  {
    id: "5",
    slug: "gaming-laptop",
    name: "Gaming Laptop Pro 15",
    description: "High-performance laptop with RTX graphics and 16GB RAM.",
    price: 1299.99,
    originalPrice: 1499.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.9,
    reviewCount: 310,
    isNew: true,
    isSale: true,
    tags: ["Gaming", "RTX", "Performance"],
  },
  {
    id: "6",
    slug: "running-shoes",
    name: "Lightweight Running Shoes",
    description: "Breathable and cushioned running shoes for everyday training.",
    price: 89.99,
    originalPrice: 119.99,
    imageUrl: productImage.src,
    category: "Footwear",
    rating: 4.4,
    reviewCount: 202,
    isNew: false,
    isSale: true,
    tags: ["Running", "Comfort", "Sport"],
  },
  {
    id: "7",
    slug: "wireless-earbuds",
    name: "True Wireless Earbuds",
    description: "Compact earbuds with 30-hour battery life and water resistance.",
    price: 79.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.2,
    reviewCount: 156,
    isNew: true,
    isSale: false,
    tags: ["Wireless", "Bluetooth", "Compact"],
  },
  {
    id: "8",
    slug: "ceramic-mug-set",
    name: "Ceramic Mug Set (4 pcs)",
    description: "Elegant ceramic mugs with matte finish, perfect for coffee or tea.",
    price: 34.99,
    imageUrl: productImage.src,
    category: "Home & Kitchen",
    rating: 4.7,
    reviewCount: 82,
    isNew: false,
    isSale: false,
    tags: ["Ceramic", "Kitchen", "Drinkware"],
  },
  {
    id: "9",
    slug: "smartphone-case",
    name: "Shockproof Smartphone Case",
    description: "Durable case with raised edges and shock-absorbing corners.",
    price: 19.99,
    imageUrl: productImage.src,
    category: "Accessories",
    rating: 4.5,
    reviewCount: 290,
    isNew: true,
    isSale: false,
    tags: ["Case", "Shockproof", "Durable"],
  },
  {
    id: "10",
    slug: "wireless-keyboard-mouse",
    name: "Wireless Keyboard & Mouse Combo",
    description: "Slim wireless keyboard and mouse with long battery life.",
    price: 49.99,
    originalPrice: 69.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.3,
    reviewCount: 178,
    isNew: false,
    isSale: true,
    tags: ["Wireless", "Keyboard", "Mouse"],
  },

  // ---- New Products ----
  {
    id: "11",
    slug: "fitness-smartwatch",
    name: "Fitness Smartwatch",
    description: "Track your steps, heart rate, and workouts with this modern smartwatch.",
    price: 199.99,
    originalPrice: 249.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.6,
    reviewCount: 215,
    isNew: true,
    isSale: true,
    tags: ["Fitness", "Smartwatch", "Wearable"],
  },
  {
    id: "12",
    slug: "espresso-coffee-machine",
    name: "Espresso Coffee Machine",
    description: "Brew rich espresso and cappuccinos with a single touch.",
    price: 349.99,
    originalPrice: 399.99,
    imageUrl: productImage.src,
    category: "Home & Kitchen",
    rating: 4.8,
    reviewCount: 98,
    isNew: true,
    isSale: true,
    tags: ["Coffee", "Espresso", "Kitchen"],
  },
  {
    id: "13",
    slug: "wireless-gaming-mouse",
    name: "Wireless Gaming Mouse",
    description: "Ultra-light gaming mouse with customizable RGB lighting.",
    price: 69.99,
    originalPrice: 89.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.5,
    reviewCount: 350,
    isNew: true,
    isSale: true,
    tags: ["Gaming", "Wireless", "RGB"],
  },
  {
    id: "14",
    slug: "noise-cancelling-microphone",
    name: "Noise Cancelling Microphone",
    description: "Crystal-clear voice recording for streaming and calls.",
    price: 129.99,
    originalPrice: 149.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.7,
    reviewCount: 143,
    isNew: false,
    isSale: true,
    tags: ["Microphone", "Streaming", "Noise Cancelling"],
  },
  {
    id: "15",
    slug: "smart-home-speaker",
    name: "Smart Home Speaker",
    description: "Voice-controlled smart speaker with built-in assistant.",
    price: 99.99,
    originalPrice: 129.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.4,
    reviewCount: 500,
    isNew: false,
    isSale: true,
    tags: ["Smart Home", "Speaker", "Voice Assistant"],
  },
  {
    id: "16",
    slug: "wooden-dining-table",
    name: "Wooden Dining Table",
    description: "Solid oak dining table with a natural finish.",
    price: 499.99,
    originalPrice: 599.99,
    imageUrl: productImage.src,
    category: "Home & Kitchen",
    rating: 4.9,
    reviewCount: 77,
    isNew: true,
    isSale: true,
    tags: ["Wood", "Dining", "Furniture"],
  },
  {
    id: "17",
    slug: "wireless-charging-pad",
    name: "Wireless Charging Pad",
    description: "Fast charging pad compatible with all Qi-enabled devices.",
    price: 39.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.2,
    reviewCount: 210,
    isNew: false,
    isSale: false,
    tags: ["Wireless", "Charging", "Portable"],
  },
  {
    id: "18",
    slug: "travel-suitcase",
    name: "Hard Shell Travel Suitcase",
    description: "Durable polycarbonate suitcase with TSA lock.",
    price: 229.99,
    originalPrice: 279.99,
    imageUrl: productImage.src,
    category: "Accessories",
    rating: 4.7,
    reviewCount: 134,
    isNew: true,
    isSale: true,
    tags: ["Travel", "Suitcase", "Durable"],
  },
  {
    id: "19",
    slug: "dslr-camera",
    name: "Professional DSLR Camera",
    description: "Capture stunning images with 24MP and 4K video.",
    price: 899.99,
    originalPrice: 1099.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.8,
    reviewCount: 312,
    isNew: false,
    isSale: true,
    tags: ["Camera", "DSLR", "Photography"],
  },
  {
    id: "20",
    slug: "office-chair",
    name: "Ergonomic Office Chair",
    description: "Adjustable office chair with lumbar support and mesh back.",
    price: 259.99,
    originalPrice: 329.99,
    imageUrl: productImage.src,
    category: "Home & Kitchen",
    rating: 4.6,
    reviewCount: 420,
    isNew: true,
    isSale: true,
    tags: ["Office", "Chair", "Ergonomic"],
  },

  // ---- Continue till 30 (add similar unique realistic ones) ----
  {
    id: "21",
    slug: "yoga-mat",
    name: "Non-Slip Yoga Mat",
    description: "Eco-friendly yoga mat with extra cushioning.",
    price: 45.99,
    imageUrl: productImage.src,
    category: "Sports & Outdoors",
    rating: 4.7,
    reviewCount: 85,
    isNew: true,
    isSale: false,
    tags: ["Yoga", "Fitness", "Eco"],
  },
  {
    id: "22",
    slug: "air-purifier",
    name: "HEPA Air Purifier",
    description: "Removes 99.97% of airborne particles for cleaner indoor air.",
    price: 149.99,
    imageUrl: productImage.src,
    category: "Home & Kitchen",
    rating: 4.5,
    reviewCount: 192,
    isNew: false,
    isSale: true,
    tags: ["Air", "Purifier", "HEPA"],
  },
  {
    id: "23",
    slug: "gaming-chair",
    name: "Racing Style Gaming Chair",
    description: "Comfortable gaming chair with recline and footrest.",
    price: 329.99,
    originalPrice: 399.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.6,
    reviewCount: 248,
    isNew: true,
    isSale: true,
    tags: ["Gaming", "Chair", "Comfort"],
  },
  {
    id: "24",
    slug: "blender",
    name: "High-Speed Blender",
    description: "Perfect for smoothies, soups, and sauces with 6 stainless blades.",
    price: 89.99,
    imageUrl: productImage.src,
    category: "Home & Kitchen",
    rating: 4.4,
    reviewCount: 142,
    isNew: false,
    isSale: false,
    tags: ["Blender", "Kitchen", "Smoothies"],
  },
  {
    id: "25",
    slug: "gaming-console",
    name: "Next-Gen Gaming Console",
    description: "Play the latest AAA titles in 4K HDR with ultra-fast loading.",
    price: 499.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.9,
    reviewCount: 654,
    isNew: true,
    isSale: false,
    tags: ["Gaming", "Console", "4K"],
  },
  {
    id: "26",
    slug: "winter-jacket",
    name: "Insulated Winter Jacket",
    description: "Stay warm with down insulation and water-resistant shell.",
    price: 199.99,
    originalPrice: 249.99,
    imageUrl: productImage.src,
    category: "Clothing",
    rating: 4.7,
    reviewCount: 99,
    isNew: true,
    isSale: true,
    tags: ["Jacket", "Winter", "Insulated"],
  },
  {
    id: "27",
    slug: "robot-vacuum",
    name: "Robot Vacuum Cleaner",
    description: "Automatic vacuum cleaner with smart navigation and app control.",
    price: 299.99,
    originalPrice: 349.99,
    imageUrl: productImage.src,
    category: "Home & Kitchen",
    rating: 4.6,
    reviewCount: 288,
    isNew: false,
    isSale: true,
    tags: ["Robot", "Vacuum", "Smart Home"],
  },
  {
    id: "28",
    slug: "tablet-pro",
    name: "Tablet Pro 11",
    description: "Powerful tablet with 11-inch display and stylus support.",
    price: 649.99,
    originalPrice: 699.99,
    imageUrl: productImage.src,
    category: "Electronics",
    rating: 4.8,
    reviewCount: 412,
    isNew: true,
    isSale: true,
    tags: ["Tablet", "Stylus", "Portable"],
  },
  {
    id: "29",
    slug: "sneakers",
    name: "Casual Sneakers",
    description: "Stylish sneakers with breathable fabric and cushioned sole.",
    price: 79.99,
    imageUrl: productImage.src,
    category: "Footwear",
    rating: 4.3,
    reviewCount: 186,
    isNew: true,
    isSale: false,
    tags: ["Sneakers", "Casual", "Comfort"],
  },
  {
    id: "30",
    slug: "dslr-tripod",
    name: "Adjustable DSLR Tripod",
    description: "Lightweight aluminum tripod with 360-degree swivel.",
    price: 119.99,
    imageUrl: productImage.src,
    category: "Accessories",
    rating: 4.5,
    reviewCount: 75,
    isNew: false,
    isSale: false,
    tags: ["Tripod", "Photography", "DSLR"],
  },
];
